# docker-compose.yml
version: "3.9"

services:
  api:
    build: .
    container_name: concert_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - database_network
      
    
networks:
  database_network:
    external: true
